export const FETCH_UPLOADED_PHOTOS_SUCCESS = 'FETCH_UPLOADED_PHOTOS_SUCCESS';
export const FETCH_UPLOADED_PHOTOS_ERROR = 'FETCH_UPLOADED_PHOTOS_ERROR';
export const STORE_SELECTED_PHOTOS = 'STORE_SELECTED_PHOTOS';
export const SAVE_SELECTION_SUCCESS = 'SAVE_SELECTION_SUCCESS';
export const SAVE_SELECTION_ERROR = 'SAVE_SELECTION_ERROR';
export const FETCH_SAVED_PHOTOS = 'FETCH_SAVED_PHOTOS';
