// Action constants for redux actions
export const FETCH_UPLOADED_PHOTOS_SUCCESS = 'FETCH_UPLOADED_PHOTOS_SUCCESS';
export const STORE_SELECTED_PHOTOS = 'STORE_SELECTED_PHOTOS';
export const SAVE_SELECTION_SUCCESS = 'SAVE_SELECTION_SUCCESS';
export const SAVE_SELECTION_ERROR = 'SAVE_SELECTION_ERROR';
export const FETCH_PHOTO_GRID_SUCCESS = 'FETCH_PHOTO_GRID_SUCCESS';
export const FETCH_PHOTO_GRID_PENDING = 'FETCH_PHOTO_GRID_PENDING';
export const FETCH_PHOTO_GRID_ERROR = 'FETCH_PHOTO_GRID_ERROR';
export const UPDATE_SELECTION_SUCCESS = 'UPDATE_SELECTION_SUCCESS';
export const UPDATE_SELECTION_ERROR = 'UPDATE_SELECTION_ERROR';
